apiVersion: v1
kind: Service
metadata:
  name: order-service-metrics
  labels:
    app: order-service
spec:
  ports:
  - name: metrics
    port: 5000
    targetPort: 5000
  selector:
    app: order-service
---
apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: order-service-monitor
  namespace: monitoring
  labels:
    release: prometheus
spec:
  selector:
    matchLabels:
      app: order-service
  namespaceSelector:
    matchNames:
    - default
  endpoints:
  - port: metrics
    interval: 15s
    path: /metrics